server:
  port: 8081
   
cloud:
  aws:
    region:
      static: us-west-2
      auto: false
    credentials:
      access-key: 
      secret-key: 
      
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/altran?allowPublicKeyRetrieval=true&useSSL=false
    username: pawan
    password: pawan
